import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import LifeChecklist from "@/components/life-events/LifeChecklist";
import AdSlot from "@/components/ads/AdSlot";
import { getLifeEvent } from "@/lib/api/life-events";
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const event=await getLifeEvent(slug);return event?{title:event.title,description:event.description,alternates:{canonical:`/life-events/${event.slug}`},openGraph:{title:event.title,description:event.description,type:"article"}}:{title:"생활상황을 찾을 수 없습니다"}}
export default async function LifeEventPage({params}:Props){const {slug}=await params;const event=await getLifeEvent(slug);if(!event)notFound();const structured={"@context":"https://schema.org","@type":"HowTo",name:event.title,description:event.description,totalTime:`PT${event.tasks.reduce((sum,t)=>sum+(t.estimated_minutes??0),0)}M`,step:event.tasks.map((task,index)=>({"@type":"HowToStep",position:index+1,name:task.title,text:task.description,url:task.official_url??undefined}))};return <main className="mx-auto min-h-screen max-w-4xl px-6 py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><nav aria-label="breadcrumb" className="text-sm text-gray-500"><Link href="/">홈</Link> / <Link href="/life-events">생활상황</Link> / {event.short_label}</nav><header className="mt-8"><span className="text-5xl" aria-hidden>{event.icon}</span><p className="mt-5 text-sm font-semibold text-blue-700">{event.category} · {event.task_count}단계</p><h1 className="mt-3 text-4xl font-bold">{event.title}</h1><p className="mt-4 text-lg leading-8 text-gray-600">{event.description}</p><p className="mt-3 text-xs text-gray-500">마지막 정보 검토: {event.reviewed_at?new Date(event.reviewed_at).toLocaleDateString("ko-KR"):"검토 예정"}</p></header><AdSlot slot={process.env.NEXT_PUBLIC_AD_LIFE_EVENT_SLOT} className="mt-10"/><div className="mt-10"><LifeChecklist event={event}/></div></main>}
