"use client";
import { FormEvent, useEffect, useState } from "react";
import { createAdminGuide, getAdminFeedback, getAdminGuides, getAnalyticsSummary, getRevenueSummary } from "@/lib/api/admin-monetization";
import type { Guide } from "@/types/monetization";

export default function MonetizationDashboard() {
  const [guides, setGuides] = useState<Guide[]>([]); const [metrics, setMetrics] = useState<Record<string, unknown>>({}); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([getAdminGuides(), getAnalyticsSummary(), getRevenueSummary(), getAdminFeedback()]).then(([g, a, r, feedback]) => { setGuides(g); setMetrics({ analytics: a, revenue: r, feedback }); }).catch((e: Error) => setError(e.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { const saved = await createAdminGuide({ slug: data.get("slug"), title: data.get("title"), summary: data.get("summary"), content: data.get("content"), category: data.get("category"), status: data.get("status"), service_ids: String(data.get("service_ids") ?? "").split(",").map(Number).filter(Boolean) }); setGuides((items) => [saved, ...items]); form.reset(); } catch (e) { setError(e instanceof Error ? e.message : "저장 실패"); } }
  return <section className="mt-14 space-y-8"><div><h2 className="text-2xl font-bold">수익화 운영</h2><p className="mt-2 text-sm text-gray-500">실제 기록된 데이터만 표시하며 값이 없으면 0 또는 null입니다.</p></div>{error && <p role="alert" className="text-red-700">{error}</p>}<details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold">수익·전환 지표</summary><pre className="mt-4 overflow-auto text-xs">{JSON.stringify(metrics, null, 2)}</pre></details><div className="grid gap-8 lg:grid-cols-[1fr_1.5fr]"><form onSubmit={submit} className="space-y-3 rounded-xl border bg-white p-5"><h3 className="font-bold">가이드 작성</h3>{["slug","title","category"].map((name) => <input key={name} name={name} required placeholder={name} className="w-full rounded border px-3 py-2" />)}<textarea name="summary" required placeholder="요약" className="w-full rounded border px-3 py-2"/><textarea name="content" required placeholder="본문" className="min-h-40 w-full rounded border px-3 py-2"/><input name="service_ids" placeholder="관련 서비스 ID: 1,2" className="w-full rounded border px-3 py-2"/><select name="status" className="w-full rounded border px-3 py-2"><option value="draft">초안</option><option value="published">게시</option></select><button className="rounded bg-gray-950 px-4 py-2 text-white">저장</button></form><div className="space-y-3">{guides.map((guide) => <article key={guide.id} className="rounded-xl border bg-white p-4"><p className="font-semibold">{guide.title}</p><p className="text-sm text-gray-500">{guide.status} · /guides/{guide.slug}</p></article>)}</div></div></section>;
}
