"""add life event navigation

Revision ID: 1efad18ccc44
Revises: 4b44172726d4
Create Date: 2026-08-22 00:30:18.579459

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1efad18ccc44"
down_revision: str | Sequence[str] | None = "4b44172726d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "life_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("short_label", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("icon", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("audience", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_life_events")),
    )
    op.create_index(
        op.f("ix_life_events_category"), "life_events", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_life_events_is_published"),
        "life_events",
        ["is_published"],
        unique=False,
    )
    op.create_index(op.f("ix_life_events_slug"), "life_events", ["slug"], unique=True)
    op.create_table(
        "life_event_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("life_event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("why_it_matters", sa.String(length=500), nullable=False),
        sa.Column(
            "task_type", sa.String(length=30), server_default="required", nullable=False
        ),
        sa.Column("timing_label", sa.String(length=100), nullable=False),
        sa.Column("deadline_days", sa.Integer(), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("required_documents", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("official_url", sa.String(length=1000), nullable=True),
        sa.Column("official_source", sa.String(length=160), nullable=True),
        sa.Column("caution", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["life_event_id"],
            ["life_events.id"],
            name=op.f("fk_life_event_tasks_life_event_id_life_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_life_event_tasks")),
    )
    op.create_index(
        op.f("ix_life_event_tasks_life_event_id"),
        "life_event_tasks",
        ["life_event_id"],
        unique=False,
    )
    op.create_table(
        "user_life_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("life_event_id", sa.Integer(), nullable=False),
        sa.Column(
            "started_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["life_event_id"],
            ["life_events.id"],
            name=op.f("fk_user_life_plans_life_event_id_life_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_life_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_life_plans")),
        sa.UniqueConstraint(
            "user_id",
            "life_event_id",
            "started_on",
            name="uq_user_life_plan_event_date",
        ),
    )
    op.create_index(
        op.f("ix_user_life_plans_life_event_id"),
        "user_life_plans",
        ["life_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_life_plans_status"), "user_life_plans", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_life_plans_user_id"), "user_life_plans", ["user_id"], unique=False
    )
    op.create_table(
        "life_event_task_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_life_event_task_services_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["life_event_tasks.id"],
            name=op.f("fk_life_event_task_services_task_id_life_event_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_life_event_task_services")),
        sa.UniqueConstraint("task_id", "service_id", name="uq_life_event_task_service"),
    )
    op.create_index(
        op.f("ix_life_event_task_services_service_id"),
        "life_event_task_services",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_life_event_task_services_task_id"),
        "life_event_task_services",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "user_task_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["user_life_plans.id"],
            name=op.f("fk_user_task_progress_plan_id_user_life_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["life_event_tasks.id"],
            name=op.f("fk_user_task_progress_task_id_life_event_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_task_progress")),
        sa.UniqueConstraint(
            "plan_id", "task_id", name="uq_user_task_progress_plan_task"
        ),
    )
    op.create_index(
        op.f("ix_user_task_progress_plan_id"),
        "user_task_progress",
        ["plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_task_progress_task_id"),
        "user_task_progress",
        ["task_id"],
        unique=False,
    )
    events = sa.table(
        "life_events",
        sa.column("id", sa.Integer),
        sa.column("slug", sa.String),
        sa.column("title", sa.String),
        sa.column("short_label", sa.String),
        sa.column("description", sa.String),
        sa.column("icon", sa.String),
        sa.column("category", sa.String),
        sa.column("audience", sa.JSON),
        sa.column("is_published", sa.Boolean),
        sa.column("display_order", sa.Integer),
        sa.column("reviewed_at", sa.DateTime(timezone=True)),
    )
    reviewed_at = datetime(2026, 8, 22, tzinfo=UTC)
    op.bulk_insert(
        events,
        [
            {
                "id": 1,
                "slug": "moving-home",
                "title": "이사 전후 해야 할 일",
                "short_label": "이사했어요",
                "description": "주소 변경부터 공공요금과 생활 계약까지 순서대로 확인합니다.",
                "icon": "🏠",
                "category": "주거",
                "audience": ["이사", "독립"],
                "is_published": True,
                "display_order": 1,
                "reviewed_at": reviewed_at,
            },
            {
                "id": 2,
                "slug": "leaving-job",
                "title": "퇴사 후 해야 할 일",
                "short_label": "퇴사했어요",
                "description": "고용·보험·연금·세금과 다음 구직 준비를 빠뜨리지 않게 관리합니다.",
                "icon": "📦",
                "category": "고용",
                "audience": ["퇴사", "구직"],
                "is_published": True,
                "display_order": 2,
                "reviewed_at": reviewed_at,
            },
            {
                "id": 3,
                "slug": "first-job",
                "title": "첫 취업 후 해야 할 일",
                "short_label": "취업했어요",
                "description": "근로계약부터 4대보험, 세금과 경력 관리를 시작합니다.",
                "icon": "💼",
                "category": "고용",
                "audience": ["사회초년생", "취업"],
                "is_published": True,
                "display_order": 3,
                "reviewed_at": reviewed_at,
            },
            {
                "id": 4,
                "slug": "starting-business",
                "title": "창업 전에 해야 할 일",
                "short_label": "창업하려고 해요",
                "description": "사업 검증, 등록, 세금과 지원사업 준비를 실행 순서로 정리합니다.",
                "icon": "🚀",
                "category": "창업",
                "audience": ["예비창업자", "사업자"],
                "is_published": True,
                "display_order": 4,
                "reviewed_at": reviewed_at,
            },
            {
                "id": 5,
                "slug": "new-baby",
                "title": "아이 출생 후 해야 할 일",
                "short_label": "아이가 태어났어요",
                "description": "출생신고와 복지·돌봄 지원 확인을 한 흐름으로 관리합니다.",
                "icon": "👶",
                "category": "가족",
                "audience": ["출산", "육아"],
                "is_published": True,
                "display_order": 5,
                "reviewed_at": reviewed_at,
            },
        ],
    )
    tasks = sa.table(
        "life_event_tasks",
        sa.column("id", sa.Integer),
        sa.column("life_event_id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("description", sa.Text),
        sa.column("why_it_matters", sa.String),
        sa.column("task_type", sa.String),
        sa.column("timing_label", sa.String),
        sa.column("deadline_days", sa.Integer),
        sa.column("estimated_minutes", sa.Integer),
        sa.column("required_documents", sa.JSON),
        sa.column("official_url", sa.String),
        sa.column("official_source", sa.String),
        sa.column("caution", sa.String),
        sa.column("display_order", sa.Integer),
    )
    common_caution = "자격과 처리 기한은 개인 상황과 제도 변경에 따라 달라질 수 있으므로 공식 기관에서 최종 확인하세요."
    op.bulk_insert(
        tasks,
        [
            {
                "id": 1,
                "life_event_id": 1,
                "title": "전입신고 확인",
                "description": "새 주소지 전입신고 방법과 세대 구성을 확인합니다.",
                "why_it_matters": "주소 기반 행정 서비스와 우편 안내의 기준이 됩니다.",
                "task_type": "required",
                "timing_label": "이사 직후",
                "deadline_days": 14,
                "estimated_minutes": 15,
                "required_documents": ["신분증", "임대차계약서(해당 시)"],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 1,
            },
            {
                "id": 2,
                "life_event_id": 1,
                "title": "임대차 계약과 확정일자 확인",
                "description": "임차인이라면 계약서와 확정일자 필요 여부를 확인합니다.",
                "why_it_matters": "임차보증금 보호와 관련될 수 있습니다.",
                "task_type": "required",
                "timing_label": "계약·입주 시",
                "deadline_days": None,
                "estimated_minutes": 20,
                "required_documents": ["임대차계약서", "신분증"],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 2,
            },
            {
                "id": 3,
                "life_event_id": 1,
                "title": "주소·공공요금 변경 목록 점검",
                "description": "우편, 전기, 가스, 수도, 통신, 보험과 금융기관 주소를 점검합니다.",
                "why_it_matters": "요금 누락과 중요 안내 분실을 예방합니다.",
                "task_type": "recommended",
                "timing_label": "이사 전후 1주",
                "deadline_days": 7,
                "estimated_minutes": 30,
                "required_documents": [],
                "official_url": None,
                "official_source": None,
                "caution": "계약 사업자별 변경 절차를 확인하세요.",
                "display_order": 3,
            },
            {
                "id": 4,
                "life_event_id": 1,
                "title": "자동차·생활 계약 주소 확인",
                "description": "차량과 정기배송 등 이전 주소가 남은 계약을 확인합니다.",
                "why_it_matters": "고지서 누락과 배송 오류를 줄입니다.",
                "task_type": "recommended",
                "timing_label": "이사 후 2주 이내",
                "deadline_days": 14,
                "estimated_minutes": 20,
                "required_documents": [],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 4,
            },
            {
                "id": 5,
                "life_event_id": 2,
                "title": "퇴직금과 퇴직 서류 확인",
                "description": "퇴직금 지급 조건과 경력증명서·원천징수영수증 수령 여부를 확인합니다.",
                "why_it_matters": "정산과 다음 취업 과정에 필요한 자료입니다.",
                "task_type": "required",
                "timing_label": "퇴사 전후",
                "deadline_days": None,
                "estimated_minutes": 20,
                "required_documents": ["근로계약서", "급여명세서"],
                "official_url": "https://www.work24.go.kr/",
                "official_source": "고용24",
                "caution": common_caution,
                "display_order": 1,
            },
            {
                "id": 6,
                "life_event_id": 2,
                "title": "실업급여 자격과 구직등록 확인",
                "description": "고용보험 이력과 비자발적 이직 등 자격 요건을 공식 안내에서 확인합니다.",
                "why_it_matters": "신청 절차와 구직활동 요건이 연결됩니다.",
                "task_type": "conditional",
                "timing_label": "퇴사 직후",
                "deadline_days": None,
                "estimated_minutes": 30,
                "required_documents": ["이직확인서 처리 여부", "신분증"],
                "official_url": "https://www.work24.go.kr/",
                "official_source": "고용24",
                "caution": common_caution,
                "display_order": 2,
            },
            {
                "id": 7,
                "life_event_id": 2,
                "title": "건강보험·국민연금 상태 확인",
                "description": "직장가입 종료 후 지역가입, 피부양자 또는 임의가입 가능성을 확인합니다.",
                "why_it_matters": "보험료와 가입 공백에 영향을 줄 수 있습니다.",
                "task_type": "required",
                "timing_label": "퇴사 후 안내 수신 시",
                "deadline_days": None,
                "estimated_minutes": 25,
                "required_documents": [],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 3,
            },
            {
                "id": 8,
                "life_event_id": 2,
                "title": "세금 정산 일정 기록",
                "description": "중도퇴사 연말정산과 다음 해 종합소득세 확인 필요성을 기록합니다.",
                "why_it_matters": "공제 누락이나 신고 지연을 예방합니다.",
                "task_type": "conditional",
                "timing_label": "퇴사 시 및 다음 신고기간",
                "deadline_days": None,
                "estimated_minutes": 20,
                "required_documents": ["근로소득 원천징수영수증"],
                "official_url": "https://www.hometax.go.kr/",
                "official_source": "홈택스",
                "caution": common_caution,
                "display_order": 4,
            },
            {
                "id": 9,
                "life_event_id": 3,
                "title": "근로계약서 보관",
                "description": "임금, 근무시간, 휴일과 계약기간을 확인하고 사본을 보관합니다.",
                "why_it_matters": "근로조건을 확인할 수 있는 기본 문서입니다.",
                "task_type": "required",
                "timing_label": "입사일",
                "deadline_days": 0,
                "estimated_minutes": 15,
                "required_documents": ["근로계약서"],
                "official_url": "https://www.work24.go.kr/",
                "official_source": "고용24",
                "caution": common_caution,
                "display_order": 1,
            },
            {
                "id": 10,
                "life_event_id": 3,
                "title": "4대보험 가입 상태 확인",
                "description": "입사 후 건강보험·국민연금·고용보험·산재보험 반영 여부를 확인합니다.",
                "why_it_matters": "보험 자격과 향후 급여·지원 신청에 영향을 줍니다.",
                "task_type": "required",
                "timing_label": "입사 후",
                "deadline_days": None,
                "estimated_minutes": 20,
                "required_documents": [],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 2,
            },
            {
                "id": 11,
                "life_event_id": 3,
                "title": "급여명세와 세금 기록 시작",
                "description": "매월 급여명세서를 보관하고 공제 항목을 확인합니다.",
                "why_it_matters": "소득·세금·보험료를 검토할 근거가 됩니다.",
                "task_type": "recommended",
                "timing_label": "첫 급여일부터 매월",
                "deadline_days": None,
                "estimated_minutes": 10,
                "required_documents": ["급여명세서"],
                "official_url": "https://www.hometax.go.kr/",
                "official_source": "홈택스",
                "caution": common_caution,
                "display_order": 3,
            },
            {
                "id": 12,
                "life_event_id": 3,
                "title": "경력·교육 계획 세우기",
                "description": "직무 목표와 필요한 교육·자격을 기록하고 지원 가능한 훈련을 확인합니다.",
                "why_it_matters": "첫 직장 경험을 다음 성장으로 연결합니다.",
                "task_type": "recommended",
                "timing_label": "입사 후 1개월",
                "deadline_days": 30,
                "estimated_minutes": 30,
                "required_documents": [],
                "official_url": "https://www.work24.go.kr/",
                "official_source": "고용24",
                "caution": common_caution,
                "display_order": 4,
            },
            {
                "id": 13,
                "life_event_id": 4,
                "title": "고객 문제와 사업 가설 정리",
                "description": "누구의 어떤 문제를 해결하고 수익을 얻는지 한 문장으로 정리합니다.",
                "why_it_matters": "지원사업보다 먼저 사업의 실수요를 확인해야 합니다.",
                "task_type": "required",
                "timing_label": "사업자등록 전",
                "deadline_days": None,
                "estimated_minutes": 60,
                "required_documents": [],
                "official_url": "https://www.k-startup.go.kr/",
                "official_source": "K-Startup",
                "caution": "지원사업 선정이 사업 성공을 보장하지 않습니다.",
                "display_order": 1,
            },
            {
                "id": 14,
                "life_event_id": 4,
                "title": "사업자등록 필요 시점 확인",
                "description": "사업 형태, 업종과 인허가 여부를 검토한 뒤 등록 절차를 확인합니다.",
                "why_it_matters": "세금계산과 계약 주체가 달라질 수 있습니다.",
                "task_type": "required",
                "timing_label": "영업 시작 전",
                "deadline_days": None,
                "estimated_minutes": 30,
                "required_documents": ["신분증", "사업장 관련 서류"],
                "official_url": "https://www.hometax.go.kr/",
                "official_source": "홈택스",
                "caution": common_caution,
                "display_order": 2,
            },
            {
                "id": 15,
                "life_event_id": 4,
                "title": "세금·증빙 관리 방식 결정",
                "description": "사업용 계좌, 카드, 영수증과 세금 신고 일정을 분리해 관리합니다.",
                "why_it_matters": "매출·비용 증빙과 신고의 기반입니다.",
                "task_type": "required",
                "timing_label": "사업 시작 시",
                "deadline_days": None,
                "estimated_minutes": 45,
                "required_documents": [],
                "official_url": "https://www.hometax.go.kr/",
                "official_source": "홈택스",
                "caution": common_caution,
                "display_order": 3,
            },
            {
                "id": 16,
                "life_event_id": 4,
                "title": "지원사업 조건과 마감 비교",
                "description": "사업 단계와 지역에 맞는 공고만 골라 자부담·의무사항까지 비교합니다.",
                "why_it_matters": "지원금만 보고 신청할 때 생기는 운영 부담을 줄입니다.",
                "task_type": "recommended",
                "timing_label": "공고 기간별",
                "deadline_days": None,
                "estimated_minutes": 40,
                "required_documents": ["사업계획 초안"],
                "official_url": "https://www.k-startup.go.kr/",
                "official_source": "K-Startup",
                "caution": common_caution,
                "display_order": 4,
            },
            {
                "id": 17,
                "life_event_id": 5,
                "title": "출생신고 절차 확인",
                "description": "출생신고 방법과 가족관계 등록에 필요한 사항을 확인합니다.",
                "why_it_matters": "이후 각종 행정·복지 서비스의 기준이 됩니다.",
                "task_type": "required",
                "timing_label": "출생 후",
                "deadline_days": None,
                "estimated_minutes": 20,
                "required_documents": ["출생증명서", "신고인 신분증"],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 1,
            },
            {
                "id": 18,
                "life_event_id": 5,
                "title": "출산·양육 지원 통합 확인",
                "description": "거주 지역과 가구 조건에 맞는 출산·양육 지원을 확인합니다.",
                "why_it_matters": "중앙정부와 지자체 지원의 신청 시점이 다를 수 있습니다.",
                "task_type": "required",
                "timing_label": "출생신고 후",
                "deadline_days": None,
                "estimated_minutes": 30,
                "required_documents": ["가족관계 확인 서류(필요 시)"],
                "official_url": "https://www.bokjiro.go.kr/",
                "official_source": "복지로",
                "caution": common_caution,
                "display_order": 2,
            },
            {
                "id": 19,
                "life_event_id": 5,
                "title": "건강보험 피부양자 등록 확인",
                "description": "자녀의 건강보험 자격 반영 여부와 필요한 절차를 확인합니다.",
                "why_it_matters": "의료 이용과 보험 자격에 연결됩니다.",
                "task_type": "required",
                "timing_label": "출생신고 후",
                "deadline_days": None,
                "estimated_minutes": 20,
                "required_documents": [],
                "official_url": "https://www.gov.kr/",
                "official_source": "정부24",
                "caution": common_caution,
                "display_order": 3,
            },
            {
                "id": 20,
                "life_event_id": 5,
                "title": "돌봄·보육 계획과 일정 기록",
                "description": "아이돌봄, 어린이집 등 향후 필요한 서비스의 신청 시기를 기록합니다.",
                "why_it_matters": "대기기간과 가정의 복직 일정에 대비할 수 있습니다.",
                "task_type": "recommended",
                "timing_label": "필요 시 미리",
                "deadline_days": None,
                "estimated_minutes": 30,
                "required_documents": [],
                "official_url": "https://www.bokjiro.go.kr/",
                "official_source": "복지로",
                "caution": common_caution,
                "display_order": 4,
            },
        ],
    )
    task_services = sa.table(
        "life_event_task_services",
        sa.column("task_id", sa.Integer),
        sa.column("service_id", sa.Integer),
    )
    op.bulk_insert(
        task_services,
        [
            {"task_id": 1, "service_id": 1},
            {"task_id": 2, "service_id": 1},
            {"task_id": 4, "service_id": 1},
            {"task_id": 5, "service_id": 4},
            {"task_id": 6, "service_id": 4},
            {"task_id": 7, "service_id": 1},
            {"task_id": 8, "service_id": 2},
            {"task_id": 9, "service_id": 4},
            {"task_id": 10, "service_id": 1},
            {"task_id": 11, "service_id": 2},
            {"task_id": 12, "service_id": 4},
            {"task_id": 13, "service_id": 5},
            {"task_id": 14, "service_id": 2},
            {"task_id": 15, "service_id": 2},
            {"task_id": 16, "service_id": 5},
            {"task_id": 17, "service_id": 1},
            {"task_id": 18, "service_id": 3},
            {"task_id": 19, "service_id": 1},
            {"task_id": 20, "service_id": 3},
        ],
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('life_events','id'), (SELECT max(id) FROM life_events))"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('life_event_tasks','id'), (SELECT max(id) FROM life_event_tasks))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_task_progress_task_id"), table_name="user_task_progress"
    )
    op.drop_index(
        op.f("ix_user_task_progress_plan_id"), table_name="user_task_progress"
    )
    op.drop_table("user_task_progress")
    op.drop_index(
        op.f("ix_life_event_task_services_task_id"),
        table_name="life_event_task_services",
    )
    op.drop_index(
        op.f("ix_life_event_task_services_service_id"),
        table_name="life_event_task_services",
    )
    op.drop_table("life_event_task_services")
    op.drop_index(op.f("ix_user_life_plans_user_id"), table_name="user_life_plans")
    op.drop_index(op.f("ix_user_life_plans_status"), table_name="user_life_plans")
    op.drop_index(
        op.f("ix_user_life_plans_life_event_id"), table_name="user_life_plans"
    )
    op.drop_table("user_life_plans")
    op.drop_index(
        op.f("ix_life_event_tasks_life_event_id"), table_name="life_event_tasks"
    )
    op.drop_table("life_event_tasks")
    op.drop_index(op.f("ix_life_events_slug"), table_name="life_events")
    op.drop_index(op.f("ix_life_events_is_published"), table_name="life_events")
    op.drop_index(op.f("ix_life_events_category"), table_name="life_events")
    op.drop_table("life_events")
    # ### end Alembic commands ###
