"""add monetization platform tables

Revision ID: 4b44172726d4
Revises: c393831cc8db
Create Date: 2026-08-22 00:18:40.860336

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b44172726d4"
down_revision: str | Sequence[str] | None = "c393831cc8db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affiliate_partners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("program_name", sa.String(length=180), nullable=False),
        sa.Column("base_url", sa.String(length=1000), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_partners")),
    )
    op.create_table(
        "guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guides")),
    )
    op.create_index(op.f("ix_guides_category"), "guides", ["category"], unique=False)
    op.create_index(op.f("ix_guides_slug"), "guides", ["slug"], unique=True)
    op.create_index(op.f("ix_guides_status"), "guides", ["status"], unique=False)
    op.create_table(
        "payment_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
        sa.UniqueConstraint(
            "provider_event_id", name=op.f("uq_payment_events_provider_event_id")
        ),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "billing_interval",
            sa.String(length=20),
            server_default="month",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    plans = sa.table(
        "plans",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("price", sa.Numeric),
        sa.column("billing_interval", sa.String),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        plans,
        [
            {
                "code": "free",
                "name": "Free",
                "price": 0,
                "billing_interval": "month",
                "is_active": True,
            },
            # 운영 가격과 결제 사업자 확정 전까지 Plus checkout을 활성화하지 않습니다.
            {
                "code": "plus",
                "name": "EasyLife Plus",
                "price": 0,
                "billing_interval": "month",
                "is_active": False,
            },
        ],
    )
    op.create_table(
        "revenue_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="KRW", nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revenue_records")),
        sa.UniqueConstraint(
            "external_reference", name=op.f("uq_revenue_records_external_reference")
        ),
    )
    op.create_index(
        op.f("ix_revenue_records_occurred_at"),
        "revenue_records",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_revenue_records_source"), "revenue_records", ["source"], unique=False
    )
    op.create_table(
        "affiliate_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("guide_id", sa.Integer(), nullable=True),
        sa.Column("destination_url", sa.String(length=2000), nullable=False),
        sa.Column("disclosure", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
            name=op.f("fk_affiliate_links_guide_id_guides"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["affiliate_partners.id"],
            name=op.f("fk_affiliate_links_partner_id_affiliate_partners"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_affiliate_links_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_links")),
    )
    op.create_index(
        op.f("ix_affiliate_links_guide_id"),
        "affiliate_links",
        ["guide_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_affiliate_links_partner_id"),
        "affiliate_links",
        ["partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_affiliate_links_service_id"),
        "affiliate_links",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_name", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.String(length=100), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("guide_id", sa.Integer(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
            name=op.f("fk_analytics_events_guide_id_guides"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_analytics_events_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_analytics_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    op.create_index(
        op.f("ix_analytics_events_client_id"),
        "analytics_events",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_created_at"),
        "analytics_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_event_name"),
        "analytics_events",
        ["event_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_guide_id"),
        "analytics_events",
        ["guide_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_service_id"),
        "analytics_events",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_user_id"),
        "analytics_events",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "api_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("api_key_prefix", sa.String(length=16), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("plan", sa.String(length=20), server_default="free", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_api_clients_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_clients")),
        sa.UniqueConstraint("api_key_hash", name=op.f("uq_api_clients_api_key_hash")),
    )
    op.create_index(
        op.f("ix_api_clients_api_key_prefix"),
        "api_clients",
        ["api_key_prefix"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_clients_owner_user_id"),
        "api_clients",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "guide_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guide_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
            name=op.f("fk_guide_services_guide_id_guides"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_guide_services_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guide_services")),
        sa.UniqueConstraint(
            "guide_id", "service_id", name="uq_guide_services_guide_service"
        ),
    )
    op.create_index(
        op.f("ix_guide_services_guide_id"), "guide_services", ["guide_id"], unique=False
    )
    op.create_index(
        op.f("ix_guide_services_service_id"),
        "guide_services",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "service_updates", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("deadlines", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("checklist", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("marketing", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("email_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("unsubscribe_token_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "unsubscribe_token_hash",
            name=op.f("uq_notification_preferences_unsubscribe_token_hash"),
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_status"), "notifications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "sponsorships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("campaign_name", sa.String(length=180), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_sponsorships_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsorships")),
    )
    op.create_index(
        op.f("ix_sponsorships_ends_at"), "sponsorships", ["ends_at"], unique=False
    )
    op.create_index(
        op.f("ix_sponsorships_service_id"), "sponsorships", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_sponsorships_starts_at"), "sponsorships", ["starts_at"], unique=False
    )
    op.create_index(
        op.f("ix_sponsorships_status"), "sponsorships", ["status"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default="pending", nullable=False
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "provider", sa.String(length=50), server_default="sandbox", nullable=False
        ),
        sa.Column("provider_subscription_id", sa.String(length=255), nullable=True),
        sa.Column(
            "cancel_at_period_end", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscriptions_plan_id_plans")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "provider_subscription_id",
            name=op.f("uq_subscriptions_provider_subscription_id"),
        ),
    )
    op.create_index(
        op.f("ix_subscriptions_plan_id"), "subscriptions", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("interests", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("age_group", sa.String(length=30), nullable=True),
        sa.Column("employment_status", sa.String(length=50), nullable=True),
        sa.Column("housing_status", sa.String(length=50), nullable=True),
        sa.Column(
            "startup_interest", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_client_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_clients.id"],
            name=op.f("fk_api_usage_api_client_id_api_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_usage")),
    )
    op.create_index(
        op.f("ix_api_usage_api_client_id"), "api_usage", ["api_client_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_usage_created_at"), "api_usage", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_usage_created_at"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_api_client_id"), table_name="api_usage")
    op.drop_table("api_usage")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_plan_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_sponsorships_status"), table_name="sponsorships")
    op.drop_index(op.f("ix_sponsorships_starts_at"), table_name="sponsorships")
    op.drop_index(op.f("ix_sponsorships_service_id"), table_name="sponsorships")
    op.drop_index(op.f("ix_sponsorships_ends_at"), table_name="sponsorships")
    op.drop_table("sponsorships")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_guide_services_service_id"), table_name="guide_services")
    op.drop_index(op.f("ix_guide_services_guide_id"), table_name="guide_services")
    op.drop_table("guide_services")
    op.drop_index(op.f("ix_api_clients_owner_user_id"), table_name="api_clients")
    op.drop_index(op.f("ix_api_clients_api_key_prefix"), table_name="api_clients")
    op.drop_table("api_clients")
    op.drop_index(op.f("ix_analytics_events_user_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_service_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_guide_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_event_name"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_created_at"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_client_id"), table_name="analytics_events")
    op.drop_table("analytics_events")
    op.drop_index(op.f("ix_affiliate_links_service_id"), table_name="affiliate_links")
    op.drop_index(op.f("ix_affiliate_links_partner_id"), table_name="affiliate_links")
    op.drop_index(op.f("ix_affiliate_links_guide_id"), table_name="affiliate_links")
    op.drop_table("affiliate_links")
    op.drop_index(op.f("ix_revenue_records_source"), table_name="revenue_records")
    op.drop_index(op.f("ix_revenue_records_occurred_at"), table_name="revenue_records")
    op.drop_table("revenue_records")
    op.drop_table("plans")
    op.drop_table("payment_events")
    op.drop_index(op.f("ix_guides_status"), table_name="guides")
    op.drop_index(op.f("ix_guides_slug"), table_name="guides")
    op.drop_index(op.f("ix_guides_category"), table_name="guides")
    op.drop_table("guides")
    op.drop_table("affiliate_partners")
    # ### end Alembic commands ###
