"""add content trust features

Revision ID: 823d933ae994
Revises: 1efad18ccc44
Create Date: 2026-08-22 01:03:52.979538

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "823d933ae994"
down_revision: str | Sequence[str] | None = "1efad18ccc44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("page_url", sa.String(length=1000), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="new", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_requests")),
    )
    op.create_index(
        op.f("ix_feedback_requests_category"),
        "feedback_requests",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_requests_created_at"),
        "feedback_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_requests_status"),
        "feedback_requests",
        ["status"],
        unique=False,
    )
    op.add_column(
        "guides", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    reviewed = datetime(2026, 8, 22, tzinfo=UTC)
    guides = sa.table(
        "guides",
        sa.column("slug", sa.String),
        sa.column("title", sa.String),
        sa.column("summary", sa.String),
        sa.column("content", sa.Text),
        sa.column("category", sa.String),
        sa.column("status", sa.String),
        sa.column("published_at", sa.DateTime(timezone=True)),
        sa.column("reviewed_at", sa.DateTime(timezone=True)),
    )
    guide_rows = [
        (
            "after-resignation-checklist",
            "퇴사 후 가장 먼저 확인할 7가지",
            "퇴직 서류부터 실업급여, 건강보험과 세금까지 퇴사 직후의 확인 순서를 정리합니다.",
            "고용",
            "퇴사 직후에는 모든 제도를 한 번에 신청하기보다 회사에서 받아야 할 자료와 처리 완료 여부부터 확인하는 것이 안전합니다.\n\n1. 근로계약서와 최근 급여명세서를 보관합니다.\n2. 퇴직금 지급 대상과 예상 지급일을 회사에 확인합니다.\n3. 경력증명서와 근로소득 원천징수영수증 발급 방법을 확인합니다.\n4. 고용24에서 이직확인서 처리 여부와 실업급여 자격 안내를 확인합니다.\n5. 건강보험 직장가입 종료 후 지역가입 또는 피부양자 가능성을 국민건강보험공단에서 확인합니다.\n6. 국민연금 가입 상태와 납부예외 가능성을 국민연금공단에서 확인합니다.\n7. 중도퇴사 연말정산 결과와 다음 해 신고 필요성을 홈택스에서 점검합니다.\n\n실업급여 자격, 보험료와 세금은 개인의 근무기간·퇴사 사유·소득에 따라 달라집니다. 최종 판단은 고용24, 국민건강보험공단, 국민연금공단과 홈택스의 최신 안내를 이용하세요.",
        ),
        (
            "unemployment-benefit-precheck",
            "실업급여 신청 전 확인사항",
            "고용보험 이력과 이직확인서, 구직등록 등 신청 전에 확인할 핵심 항목을 설명합니다.",
            "고용",
            "실업급여는 퇴사했다는 사실만으로 자동 지급되지 않습니다. 먼저 고용보험 가입기간, 퇴사 사유와 적극적인 재취업 의사 등 기본 요건을 공식 안내에서 확인해야 합니다.\n\n회사에 이직확인서가 처리되었는지 문의하고 고용24에서 고용보험 이력을 확인하세요. 구직등록과 수급자격 신청 절차는 안내되는 순서에 맞춰 진행합니다. 퇴사 사유를 증명할 자료가 필요할 수 있으므로 근로계약서, 급여명세서, 회사와 주고받은 관련 문서를 보관하는 것이 좋습니다.\n\n신청 가능 기간과 인정되는 구직활동은 개인별로 달라질 수 있습니다. 블로그나 커뮤니티 경험담보다 고용24와 관할 고용센터의 안내를 최종 기준으로 삼으세요.",
        ),
        (
            "midyear-resignation-tax",
            "중도퇴사자 연말정산 확인 방법",
            "퇴사 시 정산과 다음 해 추가 신고 가능성을 구분해 확인합니다.",
            "세금",
            "연도 중 퇴사하면 회사가 퇴직 시점까지의 급여를 기준으로 기본적인 정산을 진행할 수 있습니다. 다만 공제자료가 충분히 반영되지 않았거나 같은 해에 재취업하지 않은 경우 다음 해 종합소득세 신고 기간에 추가 확인이 필요할 수 있습니다.\n\n회사에서 근로소득 원천징수영수증을 받아 소득과 결정세액을 확인하세요. 같은 해 새 회사에 취업했다면 이전 직장의 원천징수영수증 제출 여부를 새 회사에 확인합니다. 재취업하지 않았다면 홈택스의 신고 안내와 공제자료를 확인하세요.\n\n소득 종류와 공제 가능 여부에 따라 결과가 달라지므로 금액이 크거나 다른 사업·기타소득이 있다면 국세청 또는 세무 전문가의 확인을 권합니다.",
        ),
        (
            "moving-address-change",
            "이사할 때 주소를 변경해야 하는 곳",
            "전입신고 외에도 우편, 금융, 보험과 생활 계약의 주소 변경 대상을 정리합니다.",
            "주거",
            "이사 후에는 전입신고만으로 모든 기관의 주소가 자동 변경되는 것은 아닙니다. 행정 주소와 각 민간 계약의 고객 주소를 나누어 확인해야 합니다.\n\n정부24 또는 주민센터에서 전입신고를 확인하고 임대차계약이라면 확정일자 등 필요한 보호 절차를 별도로 검토하세요. 우편물 주소 이전, 전기·가스·수도, 인터넷과 관리비 정산도 이사 전후 일정에 맞춰 처리합니다. 은행, 카드, 보험, 통신사, 쇼핑몰 배송지와 자동차 관련 주소도 각각 변경 여부를 확인하세요.\n\n임대차 보호 절차와 신고 기한은 계약 형태에 따라 다를 수 있습니다. 정부24와 관할 주민센터의 최신 안내를 확인하세요.",
        ),
        (
            "move-in-report-vs-fixed-date",
            "전입신고와 확정일자는 무엇이 다른가요?",
            "임대차 계약에서 자주 혼동하는 두 절차의 역할과 확인 순서를 설명합니다.",
            "주거",
            "전입신고는 새로운 거주지로 주소를 옮겼다는 사실을 행정기관에 신고하는 절차입니다. 확정일자는 임대차계약서가 특정 날짜에 존재했다는 사실을 공적으로 확인받는 절차로 역할이 다릅니다.\n\n임차인의 권리 보호에는 실제 점유, 전입신고와 확정일자 등 여러 요건이 함께 관련될 수 있습니다. 계약서를 작성했다고 모든 보호가 자동 완성되는 것은 아니므로 입주 일정에 맞춰 필요한 절차를 확인해야 합니다.\n\n부동산 권리관계와 보증금 보호는 법률적 판단이 필요한 영역입니다. 정부24, 인터넷등기소, 주택임대차 관련 공식 안내를 확인하고 위험 요소가 있다면 법률 전문가에게 상담하세요.",
        ),
        (
            "first-job-contract",
            "첫 취업 근로계약서 확인사항",
            "임금, 근로시간, 휴일과 계약기간 등 서명 전에 확인할 항목을 정리합니다.",
            "고용",
            "첫 출근 전에 근로계약서를 서면으로 받고 실제로 합의한 조건과 일치하는지 확인하세요. 회사명과 근무장소, 담당 업무, 계약기간, 임금 구성, 지급일, 근로시간, 휴게시간, 휴일과 연차 항목을 차례로 살펴봅니다.\n\n수습기간이 있다면 기간과 급여 조건을 확인하고, 고정OT 또는 포괄임금처럼 추가근로 수당과 관련된 문구는 계산 기준을 질문하세요. 빈칸이 남은 계약서에 먼저 서명하지 말고 서명한 문서의 사본을 보관합니다.\n\n구체적인 계약 효력과 임금 계산은 상황에 따라 다르므로 고용노동부 공식 안내나 노무 전문가의 확인을 이용하세요.",
        ),
        (
            "first-job-social-insurance",
            "사회초년생을 위한 4대보험 확인",
            "입사 후 건강보험·국민연금·고용보험·산재보험 가입 상태를 확인하는 방법을 안내합니다.",
            "고용",
            "4대보험은 건강보험, 국민연금, 고용보험과 산재보험을 통칭합니다. 입사 후 회사가 자격 취득 신고를 처리하면 각 기관의 조회 서비스에서 가입 상태를 확인할 수 있습니다.\n\n첫 급여명세서에서 보험료 공제 항목을 확인하고, 조회 결과가 실제 입사일이나 근로조건과 다르면 회사 담당자에게 먼저 문의하세요. 이전에 지역가입자로 납부하던 건강보험료가 있다면 직장가입 전환 과정의 고지서를 함께 확인하는 것이 좋습니다.\n\n근로시간과 고용형태에 따라 적용이 달라질 수 있으므로 각 공단과 고용24의 공식 안내를 최종 기준으로 이용하세요.",
        ),
        (
            "business-registration-order",
            "개인사업자 등록 전후 순서",
            "사업 시작 전 검토부터 사업자등록, 세금 일정과 증빙 관리까지 기본 흐름을 안내합니다.",
            "창업",
            "사업자등록부터 서두르기 전에 판매할 상품이나 서비스, 고객, 비용과 인허가 필요 여부를 먼저 확인하세요. 업종에 따라 신고·허가가 선행되어야 하거나 별도 자격이 필요할 수 있습니다.\n\n사업장과 상호, 업종 코드를 정리한 뒤 홈택스 또는 세무서에서 사업자등록 절차를 확인합니다. 등록 후에는 사업용 계좌와 카드 사용 방식을 정하고 매출·매입 증빙을 사업 초기부터 분리해 보관하세요. 부가가치세와 종합소득세 등 예정된 신고 일정을 달력에 기록합니다.\n\n업종과 매출 구조에 따라 세금과 의무가 달라지므로 국세청 및 관련 인허가 기관의 안내를 확인하세요.",
        ),
        (
            "simplified-vs-general-taxpayer",
            "간이과세자와 일반과세자 확인 포인트",
            "부가가치세 유형을 선택할 때 매출 규모 외에 함께 볼 항목을 설명합니다.",
            "세금",
            "간이과세와 일반과세는 부가가치세 계산과 신고 방식에서 차이가 있습니다. 단순히 세율이 낮아 보인다는 이유만으로 선택하기보다 예상 매출, 주요 고객, 매입 비용과 세금계산서 발급 필요성을 함께 검토해야 합니다.\n\n사업자가 주 고객이라면 세금계산서 발급과 매입세액 처리 요구가 중요할 수 있고, 초기 설비나 재고 매입이 크다면 매입세액 구조를 확인해야 합니다. 업종이나 지역에 따라 간이과세 적용이 제한될 수도 있습니다.\n\n기준 금액과 적용 규정은 변경될 수 있으므로 사업자등록 시점의 홈택스 안내를 확인하고 필요한 경우 세무 전문가와 상담하세요.",
        ),
        (
            "birth-registration-support",
            "출생신고 후 지원제도 확인 순서",
            "출생신고, 건강보험, 수당과 지역 지원을 한 흐름으로 확인합니다.",
            "가족",
            "아이가 태어나면 출생신고를 기준으로 여러 행정·복지 절차가 연결됩니다. 먼저 신고 기한과 필요한 서류를 정부24 또는 주민센터에서 확인하세요.\n\n출생신고 후 건강보험 피부양자 등록 상태를 확인하고, 정부24 행복출산 원스톱서비스와 복지로에서 부모급여, 아동수당 등 신청 가능한 제도를 살펴봅니다. 지자체별 출산지원과 산후 지원은 거주지와 신청 시점에 따라 다르므로 관할 지자체 안내를 별도로 확인하세요.\n\n지원 명칭과 금액, 소득 요건은 변경될 수 있습니다. 신청 전에 복지로와 거주지 행정기관의 최신 공고를 확인하세요.",
        ),
        (
            "parental-benefits-check",
            "부모급여·아동수당 확인 방법",
            "출산 가정이 자주 찾는 현금성 지원의 대상과 신청 경로를 확인합니다.",
            "복지",
            "부모급여와 아동수당은 연령, 거주와 지급 방식 등 확인 항목이 서로 다를 수 있습니다. 출생신고가 끝났다고 모든 급여가 자동으로 신청되는 것은 아니므로 신청 완료 여부를 반드시 확인하세요.\n\n복지로와 정부24에서 현재 대상 연령, 신청 경로, 지급일과 계좌 정보를 확인합니다. 어린이집 이용 등 양육 형태가 바뀌면 지급 방식에 영향이 있는지도 함께 점검하세요. 이사나 계좌 변경 후에는 정보가 정상 반영되었는지 확인합니다.\n\n제도 내용은 매년 변경될 수 있으므로 특정 블로그의 금액보다 신청 시점의 공식 안내를 기준으로 하세요.",
        ),
        (
            "national-pension-status",
            "국민연금 가입 상태 확인이 필요한 순간",
            "취업·퇴사·창업처럼 소득 상태가 달라질 때 국민연금에서 확인할 사항을 정리합니다.",
            "연금",
            "직장을 옮기거나 퇴사하고 사업을 시작하면 국민연금 가입 유형과 보험료 부과 방식이 달라질 수 있습니다. 안내문을 기다리기만 하지 말고 가입 이력과 현재 상태를 직접 확인하는 것이 좋습니다.\n\n국민연금공단의 조회 서비스에서 가입기간과 기준소득월액을 확인하세요. 퇴사 후 소득이 없다면 납부예외 가능성과 향후 추후납부의 조건을 공식 상담으로 확인할 수 있습니다. 사업을 시작했다면 지역가입과 사업장가입 적용 여부를 살펴봅니다.\n\n연금 수령액과 납부 전략은 장기간의 재무 판단이므로 개인별 상담 결과를 바탕으로 결정하세요.",
        ),
        (
            "marriage-admin-checklist",
            "결혼 전후 행정 체크리스트",
            "혼인신고부터 주소·보험·세금과 각종 계약 변경을 순서대로 확인합니다.",
            "가족",
            "결혼식과 혼인신고는 별개의 절차입니다. 혼인신고 시점은 법적 가족관계와 여러 제도 적용에 영향을 줄 수 있으므로 두 사람이 필요한 서류와 시점을 함께 정하세요.\n\n주소를 합치는 경우 전입신고와 임대차 계약 관계를 확인하고 건강보험 피부양자 가능성, 회사의 가족수당·복지 등록, 연말정산 인적공제 요건을 각각 확인합니다. 은행과 보험의 수익자·연락처 변경은 자동으로 처리되지 않으므로 필요한 계약을 목록으로 관리하세요.\n\n세금과 보험 적용은 소득 및 생계 관계에 따라 달라질 수 있으므로 각 기관의 공식 기준을 확인하세요.",
        ),
        (
            "buying-car-checklist",
            "자동차를 구입한 뒤 확인할 일",
            "등록, 보험, 세금, 주소와 정기점검 일정을 한 번에 정리합니다.",
            "자동차",
            "자동차를 인도받기 전 차량 정보와 계약 조건, 보험 개시 시각을 확인하세요. 신차와 중고차는 등록과 확인 서류가 다를 수 있습니다.\n\n등록 명의와 자동차등록증 내용을 확인하고 취득 관련 세금과 공채 등 비용 내역을 보관합니다. 자동차보험의 운전자 범위와 보장 개시일을 확인하고, 하이패스·주차·아파트 차량 등록처럼 실제 생활에 필요한 절차도 처리합니다. 중고차라면 성능상태점검기록부와 이전등록 결과를 보관하세요.\n\n세율과 검사 일정은 차종과 등록 지역에 따라 다를 수 있으므로 자동차민원 대국민포털과 지자체 안내를 확인하세요.",
        ),
        (
            "closing-business-checklist",
            "개인사업자 폐업 전후 체크리스트",
            "거래 정산부터 폐업신고, 세금·보험과 자료 보관까지 놓치기 쉬운 순서를 안내합니다.",
            "창업",
            "영업을 멈춘 것과 사업자 폐업신고는 같은 의미가 아닙니다. 미수금과 미지급금, 재고, 임대차 계약, 직원과 거래처 정산을 먼저 목록으로 정리하세요.\n\n홈택스 또는 세무서에서 폐업신고 절차와 폐업일을 확인하고, 부가가치세와 종합소득세 등 남은 신고 일정을 기록합니다. 사업용 카드·계좌와 온라인 판매 채널을 정리하되 세무 확인에 필요한 거래내역과 증빙은 보관하세요. 직원을 고용했다면 고용·산재보험과 퇴직 관련 절차도 별도로 확인합니다.\n\n폐업 뒤에도 신고와 납부 의무가 남을 수 있으므로 국세청과 관련 공단의 공식 안내를 확인하세요.",
        ),
    ]
    op.bulk_insert(
        guides,
        [
            {
                "slug": s,
                "title": t,
                "summary": m,
                "content": c,
                "category": k,
                "status": "published",
                "published_at": reviewed,
                "reviewed_at": reviewed,
            }
            for s, t, m, k, c in guide_rows
        ],
    )

    life_events = sa.table(
        "life_events",
        sa.column("id", sa.Integer),
        sa.column("slug", sa.String),
        sa.column("title", sa.String),
        sa.column("short_label", sa.String),
        sa.column("description", sa.String),
        sa.column("icon", sa.String),
        sa.column("category", sa.String),
        sa.column("audience", sa.JSON),
        sa.column("is_published", sa.Boolean),
        sa.column("display_order", sa.Integer),
        sa.column("reviewed_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        life_events,
        [
            {
                "id": 6,
                "slug": "getting-married",
                "title": "결혼 전후 해야 할 일",
                "short_label": "결혼했어요",
                "description": "혼인신고와 주소·보험·세금·생활 계약을 함께 확인합니다.",
                "icon": "💍",
                "category": "가족",
                "audience": ["결혼", "신혼"],
                "is_published": True,
                "display_order": 6,
                "reviewed_at": reviewed,
            },
            {
                "id": 7,
                "slug": "graduating-school",
                "title": "졸업 전후 해야 할 일",
                "short_label": "졸업했어요",
                "description": "증명서, 구직 준비, 보험과 청년 지원을 순서대로 확인합니다.",
                "icon": "🎓",
                "category": "교육",
                "audience": ["졸업", "청년"],
                "is_published": True,
                "display_order": 7,
                "reviewed_at": reviewed,
            },
            {
                "id": 8,
                "slug": "buying-car",
                "title": "자동차 구입 후 해야 할 일",
                "short_label": "차를 샀어요",
                "description": "등록과 보험, 세금, 주차와 점검 일정을 관리합니다.",
                "icon": "🚗",
                "category": "자동차",
                "audience": ["신차", "중고차"],
                "is_published": True,
                "display_order": 8,
                "reviewed_at": reviewed,
            },
            {
                "id": 9,
                "slug": "closing-business",
                "title": "사업자 폐업 전후 해야 할 일",
                "short_label": "폐업하려고 해요",
                "description": "거래 정산부터 폐업신고, 세금과 보험까지 정리합니다.",
                "icon": "🧾",
                "category": "창업",
                "audience": ["폐업", "사업자"],
                "is_published": True,
                "display_order": 9,
                "reviewed_at": reviewed,
            },
            {
                "id": 10,
                "slug": "caring-for-parent",
                "title": "부모님 돌봄을 시작할 때 할 일",
                "short_label": "부모님을 돌봐야 해요",
                "description": "건강·장기요양·복지와 가족의 돌봄 계획을 확인합니다.",
                "icon": "🤝",
                "category": "돌봄",
                "audience": ["부모", "돌봄"],
                "is_published": True,
                "display_order": 10,
                "reviewed_at": reviewed,
            },
        ],
    )
    tasks = sa.table(
        "life_event_tasks",
        sa.column("id", sa.Integer),
        sa.column("life_event_id", sa.Integer),
        sa.column("title", sa.String),
        sa.column("description", sa.Text),
        sa.column("why_it_matters", sa.String),
        sa.column("task_type", sa.String),
        sa.column("timing_label", sa.String),
        sa.column("deadline_days", sa.Integer),
        sa.column("estimated_minutes", sa.Integer),
        sa.column("required_documents", sa.JSON),
        sa.column("official_url", sa.String),
        sa.column("official_source", sa.String),
        sa.column("caution", sa.String),
        sa.column("display_order", sa.Integer),
    )
    event_tasks = [
        (
            21,
            6,
            "혼인신고 시점과 서류 확인",
            "혼인신고에 필요한 증인, 신분증과 제출 방법을 확인합니다.",
            "법적 가족관계가 시작되는 핵심 절차입니다.",
            "required",
            "결혼 전후",
            None,
            20,
            ["혼인신고서", "신분증"],
            "https://www.gov.kr/",
            "정부24",
        ),
        (
            22,
            6,
            "주소와 주거 계약 정리",
            "함께 거주한다면 전입신고와 임대차 계약 관계를 확인합니다.",
            "주소와 주거 권리 관계에 영향을 줄 수 있습니다.",
            "conditional",
            "거주지 결정 후",
            None,
            20,
            ["임대차계약서"],
            "https://www.gov.kr/",
            "정부24",
        ),
        (
            23,
            6,
            "보험·회사 가족정보 확인",
            "건강보험 피부양자와 회사 복지 등록 가능성을 확인합니다.",
            "보험료와 회사 복지 적용에 관련됩니다.",
            "conditional",
            "혼인신고 후",
            None,
            20,
            [],
            "https://www.gov.kr/",
            "정부24",
        ),
        (
            24,
            6,
            "연말정산과 금융 계약 점검",
            "인적공제 요건과 보험 수익자·연락처 변경 필요성을 확인합니다.",
            "세금과 계약상 연락 누락을 예방합니다.",
            "recommended",
            "연내",
            None,
            25,
            [],
            "https://www.hometax.go.kr/",
            "홈택스",
        ),
        (
            25,
            7,
            "졸업·성적증명서 발급 경로 저장",
            "학교 증명서를 온라인으로 발급받는 방법을 확인합니다.",
            "지원서 제출 때 반복해서 필요할 수 있습니다.",
            "required",
            "졸업 직후",
            None,
            15,
            [],
            "https://www.gov.kr/",
            "정부24",
        ),
        (
            26,
            7,
            "구직등록과 이력서 준비",
            "고용24 구직등록과 기본 이력서를 준비합니다.",
            "채용 지원과 일부 청년지원의 출발점입니다.",
            "recommended",
            "졸업 전후",
            None,
            40,
            [],
            "https://www.work24.go.kr/",
            "고용24",
        ),
        (
            27,
            7,
            "건강보험 상태 확인",
            "피부양자 유지 또는 지역가입 전환 여부를 확인합니다.",
            "보험료 고지 누락을 예방합니다.",
            "required",
            "상태 변경 안내 시",
            None,
            20,
            [],
            "https://www.gov.kr/",
            "정부24",
        ),
        (
            28,
            7,
            "청년 지원정책 탐색",
            "거주지와 취업 상태에 맞는 청년 지원을 공식 포털에서 확인합니다.",
            "신청기간이 짧은 지원을 놓치지 않게 합니다.",
            "recommended",
            "매월 확인",
            None,
            30,
            [],
            "https://www.bokjiro.go.kr/",
            "복지로",
        ),
        (
            29,
            8,
            "차량 등록 내용 확인",
            "자동차등록증의 명의와 차량 정보를 확인합니다.",
            "소유권과 행정정보 오류를 조기에 발견합니다.",
            "required",
            "인도 즉시",
            None,
            15,
            ["자동차등록증"],
            "https://www.gov.kr/",
            "정부24",
        ),
        (
            30,
            8,
            "자동차보험 개시 확인",
            "운전자 범위, 보장 내용과 개시 시각을 확인합니다.",
            "보험 공백을 예방합니다.",
            "required",
            "운행 전",
            None,
            20,
            ["보험증권"],
            None,
            None,
        ),
        (
            31,
            8,
            "세금·비용 자료 보관",
            "취득 관련 세금과 등록 비용 내역을 보관합니다.",
            "비용 확인과 향후 거래에 필요할 수 있습니다.",
            "required",
            "등록 후",
            None,
            15,
            ["납부영수증"],
            "https://www.hometax.go.kr/",
            "홈택스",
        ),
        (
            32,
            8,
            "주차·하이패스·점검 일정 등록",
            "생활 이용 등록과 정기점검 일정을 달력에 기록합니다.",
            "실제 운행의 불편과 점검 누락을 줄입니다.",
            "recommended",
            "첫 주",
            None,
            20,
            [],
            None,
            None,
        ),
        (
            33,
            9,
            "거래·재고·계약 정산",
            "미수금, 미지급금, 재고와 임대차 계약을 정리합니다.",
            "폐업 후 남는 채무와 분쟁을 줄입니다.",
            "required",
            "폐업신고 전",
            None,
            60,
            ["계약서", "거래내역"],
            None,
            None,
        ),
        (
            34,
            9,
            "사업자 폐업신고",
            "홈택스 또는 세무서에서 폐업일과 신고 방법을 확인합니다.",
            "영업 중단과 행정상 폐업은 별도입니다.",
            "required",
            "영업 종료 시",
            None,
            20,
            ["사업자등록증"],
            "https://www.hometax.go.kr/",
            "홈택스",
        ),
        (
            35,
            9,
            "남은 세금 신고 일정 기록",
            "부가가치세와 종합소득세 등 남은 의무를 확인합니다.",
            "폐업 후에도 신고 의무가 남을 수 있습니다.",
            "required",
            "폐업신고 후",
            None,
            30,
            ["매출·매입 증빙"],
            "https://www.hometax.go.kr/",
            "홈택스",
        ),
        (
            36,
            9,
            "직원·보험·계정 정리",
            "직원이 있다면 고용보험과 퇴직 절차를 확인하고 사업 계정을 정리합니다.",
            "근로관계와 보험 처리 누락을 예방합니다.",
            "conditional",
            "폐업 전후",
            None,
            40,
            [],
            "https://www.work24.go.kr/",
            "고용24",
        ),
        (
            37,
            10,
            "현재 돌봄 필요도 기록",
            "진료, 식사, 이동, 복약과 일상생활 지원 필요를 가족과 정리합니다.",
            "필요한 서비스의 종류를 판단하는 기초입니다.",
            "required",
            "돌봄 시작 시",
            None,
            30,
            [],
            None,
            None,
        ),
        (
            38,
            10,
            "장기요양 인정 신청 확인",
            "국민건강보험공단에서 장기요양 인정 절차와 대상 여부를 확인합니다.",
            "공적 돌봄서비스 이용 가능성과 연결됩니다.",
            "conditional",
            "돌봄 필요 증가 시",
            None,
            30,
            ["의료 관련 자료"],
            "https://www.longtermcare.or.kr/",
            "노인장기요양보험",
        ),
        (
            39,
            10,
            "복지·돌봄 서비스 탐색",
            "복지로와 거주지 행정기관에서 이용 가능한 지원을 확인합니다.",
            "가족이 모든 돌봄을 감당하는 상황을 줄일 수 있습니다.",
            "recommended",
            "신청기간 확인",
            None,
            30,
            [],
            "https://www.bokjiro.go.kr/",
            "복지로",
        ),
        (
            40,
            10,
            "가족 역할과 비상연락 정리",
            "주 돌봄자, 병원 동행, 비용과 비상연락 방법을 문서화합니다.",
            "가족 간 역할 혼선과 돌봄 공백을 예방합니다.",
            "required",
            "가족 협의 후",
            None,
            40,
            [],
            None,
            None,
        ),
    ]
    caution = "자격, 기한과 처리 방법은 개인 상황과 제도 변경에 따라 달라질 수 있으므로 공식 기관에서 최종 확인하세요."
    op.bulk_insert(
        tasks,
        [
            {
                "id": i,
                "life_event_id": e,
                "title": t,
                "description": d,
                "why_it_matters": w,
                "task_type": ty,
                "timing_label": timing,
                "deadline_days": days,
                "estimated_minutes": mins,
                "required_documents": docs,
                "official_url": url,
                "official_source": source,
                "caution": caution,
                "display_order": ((i - 21) % 4) + 1,
            }
            for i, e, t, d, w, ty, timing, days, mins, docs, url, source in event_tasks
        ],
    )
    op.execute(
        sa.text(
            "SELECT setval(pg_get_serial_sequence('life_events','id'), (SELECT max(id) FROM life_events))"
        )
    )
    op.execute(
        sa.text(
            "SELECT setval(pg_get_serial_sequence('life_event_tasks','id'), (SELECT max(id) FROM life_event_tasks))"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM life_event_tasks WHERE id BETWEEN 21 AND 40"))
    op.execute(sa.text("DELETE FROM life_events WHERE id BETWEEN 6 AND 10"))
    op.execute(
        sa.text(
            "DELETE FROM guides WHERE slug IN ('after-resignation-checklist','unemployment-benefit-precheck','midyear-resignation-tax','moving-address-change','move-in-report-vs-fixed-date','first-job-contract','first-job-social-insurance','business-registration-order','simplified-vs-general-taxpayer','birth-registration-support','parental-benefits-check','national-pension-status','marriage-admin-checklist','buying-car-checklist','closing-business-checklist')"
        )
    )
    op.drop_column("guides", "reviewed_at")
    op.drop_index(op.f("ix_feedback_requests_status"), table_name="feedback_requests")
    op.drop_index(
        op.f("ix_feedback_requests_created_at"), table_name="feedback_requests"
    )
    op.drop_index(op.f("ix_feedback_requests_category"), table_name="feedback_requests")
    op.drop_table("feedback_requests")
    # ### end Alembic commands ###
